export default {
  comment: ["PUT", "POST", "DELETE"],
  comments: ["GET"],
  draft: ["GET"],
  drafts: ["GET"],
  entries: ["GET"],
  entry: ["GET", "PUT", "POST", "DELETE"],
  filter: ["GET", "PUT", "POST", "DELETE"],
  filters: ["GET"],
  filterOrder: ["PUT"],
  imageSize: ["PUT", "POST", "DELETE"],
  imageSizes: ["GET"],
  role: ["PUT", "POST", "DELETE"],
  roleRight: ["POST", "DELETE"],
  roleRights: ["GET"],
  setting: ["PUT"],
  tagRole: ["POST", "DELETE"],
  tagRoles: ["GET"],
  tags: ["GET"],
  token: ["PUT", "POST", "DELETE"],
  tokens: ["GET"],
  uploadImage: ["POST"],
  useToken: ["POST"],
};
